## numpy array

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
# From above it does not mean that original list gets converted as you can see below
type(my_list)

list

In [6]:
my_arr = np.array(my_list)

In [7]:
my_arr

array([1, 2, 3])

In [8]:
type(my_arr)

numpy.ndarray

In [9]:
# Creating 2D array using python list
arr = [[1,2,3],[4,5,6],[7,8,9]]

my_arr2 = np.array(arr)

In [10]:
my_arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(my_arr2)

numpy.ndarray

In [12]:
# creating array without using python list with using in-built functions
# Syntax: np.arange(start, end(but not included), step)
# NOTE: arange is almost equivalent to range function in python
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# To create array of any size with zeros or ones value contained by each element use below:
# NOTE: Keep in mind that while passing shape if you pass only number then it creates 1D array with specific floating point values (0., 1.)
# And if you are passing shape in tuple form like (2, 2) it means 2 rows and 2 columns
# For zeroes use np.zeros(shape) and for ones use np.ones(shape)

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Using linspace to create array from start to end with included end and with specified number of elements
# Syntax: np.linspace(start, end, numberOfElements)
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0, 10, 11) # NOTE: Keep in mind that as numberOfElements passed over here is 11 because in this function end is also included

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
# If you do below:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
# To create identical matrix
# Syntax: np.eye(shape(but only single number as it creates 2D with same number of rows and columns with diagonal values as 1, and remaining element values as 0.))
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Random functionality

np.random.rand(1) # when compiled always provide new value

array([0.67946038])

In [29]:
np.random.rand(5,2) # provide rows and columns

array([[0.29198011, 0.55376519],
       [0.89307883, 0.90359646],
       [0.40898251, 0.72742333],
       [0.45047502, 0.50835404],
       [0.98670074, 0.53299299]])

In [32]:
np.random.randn(10) # It can also provide negative numbers

# NOTE: Values closer to 0 will get the priority and will be choosen

array([-0.81096494,  0.52616566,  0.32200856,  1.08370962,  0.19396779,
       -1.82046027, -0.08024682,  0.68292362,  1.9793786 , -2.53571059])

In [35]:
np.random.randn(2,3) # providing rows and columns

array([[-0.72931066,  0.08601731,  1.96847119],
       [ 0.05950314, -0.21623727,  0.48466304]])

In [37]:
# randint() returns random integers

np.random.randint(0, 101, 5) # 0 inclusive and 101 exlcusive and 5 is the number of elements required

array([58, 26, 84,  5, 90])

In [39]:
np.random.randint(0, 101, (4,5)) # (4,5) means 4 rows and 5 columns

array([[ 9,  5, 66, 20, 21],
       [75, 81, 90, 55,  6],
       [89, 52, 82, 15, 18],
       [65, 69, 88, 45, 81]])

In [49]:
# Set 'seed' means seting random number of states

np.random.seed(42) # 42 means an arbitrary choice you can choose any number
np.random.rand(4)

# NOTE: Actually seed to do is that it sets a particular set of random numbers so while
# refrehing it does not get changed. 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [51]:
arr = np.arange(0, 25)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.reshape(5,5) # reshaping arrays

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr.reshape(5,4) # it shows error because we can not fit 25 elements into 5 rows 4 columns array

ValueError: cannot reshape array of size 25 into shape (5,4)

In [59]:
# max and min

ranarr = np.random.randint(0, 101, 10)

In [61]:
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [62]:
ranarr.max()

87

In [63]:
ranarr.min()

1

In [65]:
ranarr.argmax() # it returns the index value of the maximum number element

1

In [66]:
ranarr.argmin() # it returns the index value of the element having minimum value element

0

In [68]:
ranarr.dtype # data type of an array

dtype('int32')

In [73]:
arr.shape # to get shape output as 25 means having 1 row and 25 columns or containing value

(5, 5)

In [74]:
arr = arr.reshape(5,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr.shape

(5, 5)

In [77]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])