In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [7]:
arr[1:5] # from index 1 upto 5 but not including 5

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:5] # leaving the start means starting from the first element

array([0, 1, 2, 3, 4])

In [12]:
arr[5:] # leaving the end parameter means upto the last

array([ 5,  6,  7,  8,  9, 10])

In [14]:
# NOTE: In numpy we can broadcast a value for multiple set of values

arr[0:5] = 100

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11)

In [18]:
slice_of_arr = arr[0:5]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr[:] = 99 # NOTE: It makes all the element of slice_of_arr to the value 99 also in the original arr the value at the indexes sliced also gets changed

In [24]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
# So not to do broadcasting we need to create a copy of original array and then do broadcasting
arr_copy = arr.copy()

In [29]:
arr_copy[:] = 100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr # not get changed as the copy is being manipulated

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [33]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
# Slicing in 2D array

arr_2d.shape

(3, 3)

In [38]:
arr_2d[-1] # getting complete row

array([35, 40, 45])

In [40]:
# Getting specific element

# TWO WAYS

# FIRST ONE

arr_2d[1][1] # 25

25

In [41]:
# SECOND ONE

arr_2d[0, 2] # 15

15

In [42]:
# Slicing 2D array

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr = np.arange(1, 11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4 # returns numpy array of boolean values

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr > 4

In [48]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr] # returns array with element having boolean value True only

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])