## Numpy Operations

In [1]:
import numpy as np 

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 5 # perform addition of every elements by five

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr - 2 # perform subtraction of every element from two

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
arr + arr # NOTE: must be in same shape and adds one element of the arr with same indexed element of another element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# NOTE: Special in division by dividing with zero in numpy

arr / arr # gives warning but still do division

# NOTE: But 0/0 gives nan (not a number)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15520\1823984734.py:3: RuntimeWarning: invalid value encountered in divide
  arr / arr # gives warning but still do division


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
1/0 # gives error

ZeroDivisionError: division by zero

In [16]:
1/arr # NOTE: Gives infinity but also 1/0 gives inf as value which means infinity

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15520\1118022703.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr # NOTE: Gives infinity but also 1/0 gives inf as value which means infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [20]:
np.log(arr) # NOTE: Again warning as log(0) means no sense

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15520\2732960551.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # NOTE: Again warning as log(0) means no sense


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr.sum()

45

In [23]:
arr.mean()

4.5

In [24]:
arr.max()

9

In [25]:
arr.var() # this provides variants

8.25

In [26]:
arr.std() # this provides standard deviation

2.8722813232690143

In [28]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [30]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr2d.sum() # sum of all those elements

300

In [35]:
arr2d.sum(axis=0) # 0 means sum of the each elements within the columns

array([50, 55, 60, 65, 70])

In [36]:
arr2d.sum(axis=1) # 1 means sum of the each elements within the row

array([ 10,  35,  60,  85, 110])